######################################################################
# Automatically generated by qmake (3.0) Sat Nov 25 14:28:42 2017
######################################################################

TEMPLATE = app
TARGET = RT-STM32F407-DISCOVERY
INCLUDEPATH += .

# Input
HEADERS += chconf.h halconf.h mcuconf.h
SOURCES += main.c
